swagger: '2.0'
info:
  description: This document describes a subset of UniConnect Transact&trade; Open Banking API collection. These APIs are implemented in REST-like conventions, uses HTTP/1.1 and JSON messages.
  version: 1.0.0
  title: UniConnect Transact™ API
  contact:
    email: api-support@uniconnect.io
host: uniconnect-transact.azure-api.net
basePath: /
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /security/authentication/access-token:
    post:
      tags:
        - Security
      summary: Validates User's credentials, creates new server-side session and returns an Access-Token containing sessionid
      description: This operation works similar to [OAuth2's Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) flow.
      operationId: authenticateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Credentials
          description: Email and Password required
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '201':
          description: Successfully logged in.
          schema:
            $ref: '#/definitions/AccessToken'
        '401':
          description: Invalid credentials.
  /customermgmt/welcome/profile:
    get:
      security:
        - Bearer: []
      tags:
        - Customer Management
      summary: Gets User's basic profile data, such as name, dob and last login time
      description: ''
      operationId: getWelcomeProfile
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Profile received successfully.
          schema:
            $ref: '#/definitions/WelcomeProfile'
        '401':
          description: Not Authorized
        '404':
          description: User profile not found
  /customermgmt/welcome/messages:
    get:
      security:
        - Bearer: []
      tags:
        - Customer Management
      summary: Gets list of welcome messages and notices, such as new feature announcement or system maintenance notice
      description: ''
      operationId: getWelcomeMessageList
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Messages Retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/WelcomeMessage'
        '401':
          description: Not Authorized
  /customermgmt/profile/profile:
    get:
      security:
        - Bearer: []
      tags:
        - Customer Management
      summary: Gets User's full profile data, which includes biographics, demographics and contact details
      description: ''
      operationId: getCustomerProfile
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Profile received successfully.
          schema:
            $ref: '#/definitions/CustomerProfile'
        '401':
          description: Not Authorized
        '404':
          description: User profile not found
  '/customermgmt/profile/addresses/{id}':
    put:
      security:
        - Bearer: []
      tags:
        - Customer Management
      summary: Update Customer address
      description: ''
      operationId: updateAddress
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PostalAddress'
      produces:
        - application/json
      responses:
        '200':
          description: Address updated successfully
          schema:
            $ref: '#/definitions/AddressUpdateResponse'
        '401':
          description: Not Authorized
        '404':
          description: User profile not found
  /accountmgmt/retail/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Management
      summary: Gets list of retail bank accounts linked to User's login profile
      description: ''
      operationId: getRetailAccountList
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Account List retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/RetailAccount'
        '401':
          description: Not Authorized
  '/accountmgmt/retail/accounts/{id}':
    get:
      security:
        - Bearer: []
      tags:
        - Account Management
      summary: Gets account details and balances for a given account
      description: ''
      operationId: getRetailAccountDetails
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Account details retrieved successfully
          schema:
            $ref: '#/definitions/AccountDetail'
        '401':
          description: Not Authorized
  '/accountmgmt/retail/accounts/{id}/transactions':
    get:
      security:
        - Bearer: []
      tags:
        - Account Management
      summary: Gets transactions history for a given account
      description: ''
      operationId: getAccountTransactionHistory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Transaction details retrieved successfully
        - name: fromDate
          in: query
          type: string
          description: Transaction histrory start date.
          format: date
        - name: toDate
          in: query
          type: string
          description: Transaction histrory end date.
          format: date
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transactions'
        '401':
          description: Not Authorized
  '/payments/transfer/ft':
    post:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Transfer funds from one linked account to another
      description: ''
      operationId: fundTransfer
      parameters:
        - name: transaction
          in: body
          schema:
            $ref: '#/definitions/FundTransfer'
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            items:
              $ref: '#/definitions/Transactions'
        '401':
          description: Not Authorized
definitions:
  Credentials:
    type: object
    required: 
    - email
    - password
    - strategy
    - bankId
    properties:
      email:
        type: string
        description: Registered user email address.
      password:
        type: string
        description: Password associated with registered user email.
      strategy:
        type: string
        description: TODO Strategy needs to be updated.
        default: local
        enum:
        - local
        - jwt
      bankId:
        type: string
        description: Specific bank Id which is associated with the user.
  AccessToken:
    type: object
    properties:
      accessToken:
        type: string
        description: Logged in user JWT token.
  WelcomeProfile:
    type: object
    description: Short version of full customer profile object, containing only key elements
    properties:
      name:
        type: object
        properties:
          title:
            type: string
          firstName:
            type: string
          lastName:
            type: string
      lastLogin:
        type: string
        format: date-time
      birthday:
        type: string
        format: date
      gender:
        type: string
      customerType:
        type: string
  CustomerProfile:
    type: object
    properties:
      customerType:
        type: string
        description: Type of logged in customer.
      customerSegment:
        type: string
        description: Customer belonging segment.
      customerParticulars:
        description: This will contains basic personal information like firstName etc.
        properties:
          firstName:
            type: string
          lastName:
            type: string
          gender:
            type: string
          prefix:
            type: string
          suffix:
            type: string
        type: object
      demographics:
        description: Contains the customer demographic information.
        properties:
          dob:
            type: string
            format: date-time
          placeOfBirth:
            type: string
          countryOfBirth:
            type: string
          residencyCountryCode:
            type: string
          nationality:
            type: string
          maritalStatus:
            type: string
          residencyStatus:
            type: string
          residencyType:
            type: string
        type: object
      addresses:
        type: array
        description: List of postal addresses associated with User
        items:
          $ref: '#/definitions/PostalAddress'
      emails:
        type: array
        description: List of email addresses associated with User
        items:
          $ref: '#/definitions/Email'
      phones:
        type: array
        description: List of telephone numbers associated with User
        items:
          $ref: '#/definitions/Telephone'
      socialMedia:
        type: array
        description: Customer social media related information.
        items:
          type: object
          properties:
            id:
              type: number
            accountId:
              type: string
            preferred:
              type: boolean
      idDocs:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
            primary:
              type: boolean
            number:
              type: string
            expiry:
              type: string
              format: date-time
            issuancePlace:
              type: string
            issuanceCountry:
              type: string
      education:
        type: string
        description: Customer education related information.
      employment:
        type: array
        description: Customer employment related information.
        items:
          type: object
          properties:
            employerName:
              type: string
            jobTitle:
              type: string
            occupationCode:
              type: string
            description:
              type: string
            industryCode:
              type: string
            duration:
              type: string
            email:
              type: string
      financialInfo:
        type: array
        description: Customer financial related information.
        items:
          type: string
  AddressUpdateResponse: 
    type: object
    description: Response entity of addressUpdate operation
    allOf: 
    - $ref: '#/definitions/TxnResponse'
    - type: object
      properties: 
        txnResponse: 
          $ref: '#/definitions/PostalAddress' 
  WelcomeMessage:
    properties:
      title:
        type: string
      body:
        type: string
      messageType:
        type: string
      link:
        type: string
  AccountDetail:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      type:
        type: string
      balance:
        items:
          $ref: '#/definitions/AccountBalance'
  RetailAccount:
    type: object
    properties:
      accountNo:
        type: string
      currency:
        type: string
      workBalance:
        type: string
      accountType:
        type: string
      ledgerBalance:
        type: string
      clearedBalance:
        type: string
      lockBalance:
        type: string
      usableBalance:
        type: string
      accountId:
        type: number
  AccountBalance:
    type: object
    description: Customer balance related information.
    properties:
      balanceType:
        type: string
      amount:
        type: number
        format: double
      currencyCode:
        type: string
  Transactions:
    type: object
    description: Customer transaction related information.
    properties:
      transactionDate:
        type: string
        format: date-time
      description:
        type: string
      reference:
        type: string
      localCurrency:
        type: string
      debit:
        type: string
      credit:
        type: string
  FundTransfer:
    type: object
    description: Fund Transfer related information.
    required:
      - accountId
      - creditActId
      - creditAmount
    properties:
      accountId:
        type: string
      creditActId:
        type: string
      creditAmount:
        type: string
  PostalAddress:
    type: object
    description: Based on https://schema.org/PostalAddress
    properties:
      id:
        type: string
        description: Addresss identifier unique to a User, e.g. add1, 001
      type:
        type: string
        description: Business defined classification for addresses, e.g. mailing, residence
      label: 
        type: string
        description: User defined optional label for easy reference, e.g. myhome
      line1:
        type: string
      line2:
        type: string
      line3:
        type: string
      line4:
        type: string
      locality:
        type: string
        description: City/Town/Township, e.g. Mountain View
      region:
        type: string
        description: Province/Region/State, e.g. CA
      postalCode:
        type: string
      country:
        type: string
  Telephone: 
    type: object
    description: Based on https://schema.org/telephone
    properties:
      id:
        type: string
        description: Email identifier unique to a User, e.g. email01, 001
      type:
        type: string
        description: Business defined classification for emails, e.g. personal, work
      label: 
        type: string
        description: User defined optional label for easy reference, e.g. gmailid
      number:
        type: string
        description: Telephone number, e.g. +16509036300, (650) 903-6300, 6509036300
      countryCode:
        type: string
        description: Optional if already included in number, e.g. +1
      areaCode:
        type: string
        description: Optional if already included in number, e.g. 650
      ext:
        type: string
        description: Optional extension number, e.g. 100
  Email: 
    type: object
    description: Based on https://schema.org/email
    properties:
      id:
        type: string
        description: Email identifier unique to a User, e.g. email01, 001
      type:
        type: string
        description: Business defined classification for emails, e.g. personal, work
      label: 
        type: string
        description: User defined optional label for easy reference, e.g. gmailid
      email:
        type: string
        description: E-Mail address, e.g. john@example.com
      preferred:
        type: boolean
  TxnResponse: 
    type: object
    description: Generic schema representing response of a transaction process 
    properties: 
      txnId:
        type: string
        format: uuid
        description: UUID to identify this transaction within the system
      txnRef: 
        type: string
        description: Bank or system assigned transaction reference number, for Customer communication purposes
      txnStatus: 
        type: string
        description: Bank transaction processing status after acceptance, e.g. accepted, pending, queued 
